create view all_tables as
select decade, nhgisnam, statenam, geom from ak_county_1880 union
select decade, nhgisnam, statenam, geom from ak_county_1890 union
select decade, nhgisnam, statenam, geom from ak_county_1900 union
select decade, nhgisnam, statenam, geom from ak_county_1910 union
select decade, nhgisnam, statenam, geom from ak_county_1920 union
select decade, nhgisnam, statenam, geom from ak_county_1930 union
select decade, nhgisnam, statenam, geom from ak_county_1940 union
select decade, nhgisnam, statenam, geom from ak_county_1950 union
select decade, nhgisnam, statenam, geom from ak_county_1960 union
select decade, nhgisnam, statenam, geom from ak_county_1970 union
select decade, nhgisnam, statenam, geom from ak_county_1980 union
select decade, nhgisnam, statenam, geom from ak_county_1990 union
select decade, nhgisnam, statenam, geom from ak_county_2000 union
select '1880', null, statenam, geom from ak_state_1880 union
select '1890', null, statenam, geom from ak_state_1890 union
select '1900', null, statenam, geom from ak_state_1900 union
select '1910', null, statenam, geom from ak_state_1910 union
select '1920', null, statenam, geom from ak_state_1920 union
select '1930', null, statenam, geom from ak_state_1930 union
select '1940', null, statenam, geom from ak_state_1940 union
select '1950', null, statenam, geom from ak_state_1950 union
select '1960', null, statenam, geom from ak_state_1960 union
select '1970', null, statenam, geom from ak_state_1970 union
select '1980', null, statenam, geom from ak_state_1980 union
select '1990', null, statenam, geom from ak_state_1990 union
select '2000', null, statenam, geom from ak_state_2000 union
select decade, nhgisnam, statenam, geom from hi_county_1900 union
select decade, nhgisnam, statenam, geom from hi_county_1910 union
select decade, nhgisnam, statenam, geom from hi_county_1920 union
select decade, nhgisnam, statenam, geom from hi_county_1930 union
select decade, nhgisnam, statenam, geom from hi_county_1940 union
select decade, nhgisnam, statenam, geom from hi_county_1950 union
select decade, nhgisnam, statenam, geom from hi_county_1960 union
select decade, nhgisnam, statenam, geom from hi_county_1970 union
select decade, nhgisnam, statenam, geom from hi_county_1980 union
select decade, nhgisnam, statenam, geom from hi_county_1990 union
select decade, nhgisnam, statenam, geom from hi_county_2000 union
select '1900', null, statenam, geom from hi_state_1900 union
select '1910', null, statenam, geom from hi_state_1910 union
select '1920', null, statenam, geom from hi_state_1920 union
select '1930', null, statenam, geom from hi_state_1930 union
select '1940', null, statenam, geom from hi_state_1940 union
select '1950', null, statenam, geom from hi_state_1950 union
select '1960', null, statenam, geom from hi_state_1960 union
select '1970', null, statenam, geom from hi_state_1970 union
select '1980', null, statenam, geom from hi_state_1980 union
select '1990', null, statenam, geom from hi_state_1990 union
select '2000', null, statenam, geom from hi_state_2000 union
select decade, nhgisnam, statenam, geom from us_county_1790 union
select decade, nhgisnam, statenam, geom from us_county_1800 union
select decade, nhgisnam, statenam, geom from us_county_1810 union
select decade, nhgisnam, statenam, geom from us_county_1820 union
select decade, nhgisnam, statenam, geom from us_county_1830 union
select decade, nhgisnam, statenam, geom from us_county_1840 union
select decade, nhgisnam, statenam, geom from us_county_1850 union
select decade, nhgisnam, statenam, geom from us_county_1860 union
select decade, nhgisnam, statenam, geom from us_county_1870 union
select decade, nhgisnam, statenam, geom from us_county_1880 union
select decade, nhgisnam, statenam, geom from us_county_1890 union
select decade, nhgisnam, statenam, geom from us_county_1900 union
select decade, nhgisnam, statenam, geom from us_county_1910 union
select decade, nhgisnam, statenam, geom from us_county_1920 union
select decade, nhgisnam, statenam, geom from us_county_1930 union
select decade, nhgisnam, statenam, geom from us_county_1940 union
select decade, nhgisnam, statenam, geom from us_county_1950 union
select decade, nhgisnam, statenam, geom from us_county_1960 union
select decade, nhgisnam, statenam, geom from us_county_1970 union
select decade, nhgisnam, statenam, geom from us_county_1980 union
select decade, nhgisnam, statenam, geom from us_county_1990 union
select decade, nhgisnam, statenam, geom from us_county_2000 union
select '1790', null, statenam, geom from us_state_1790 union
select '1800', null, statenam, geom from us_state_1800 union
select '1810', null, statenam, geom from us_state_1810 union
select '1820', null, statenam, geom from us_state_1820 union
select '1830', null, statenam, geom from us_state_1830 union
select '1840', null, statenam, geom from us_state_1840 union
select '1850', null, statenam, geom from us_state_1850 union
select '1860', null, statenam, geom from us_state_1860 union
select '1870', null, statenam, geom from us_state_1870 union
select '1880', null, statenam, geom from us_state_1880 union
select '1890', null, statenam, geom from us_state_1890 union
select '1900', null, statenam, geom from us_state_1900 union
select '1910', null, statenam, geom from us_state_1910 union
select '1920', null, statenam, geom from us_state_1920 union
select '1930', null, statenam, geom from us_state_1930 union
select '1940', null, statenam, geom from us_state_1940 union
select '1950', null, statenam, geom from us_state_1950 union
select '1960', null, statenam, geom from us_state_1960 union
select '1970', null, statenam, geom from us_state_1970 union
select '1980', null, statenam, geom from us_state_1980 union
select '1990', null, statenam, geom from us_state_1990 union
select '2000', null, statenam, geom from us_state_2000;
