key_tags = [
    "place",
    "amenity",
    "leisure",
    "tourism",
    "man_made",
    "natural",
    "historic",
    "landuse",
    "military",
    "railway",
    "aeroway",
    "building"
]

admin_level_map = {
    "1": "PCL",
    "2": "PCL",
    "3": "ADM1",
    "4": "ADM1",
    "5": "ADM2",
    "6": "ADM2",
    "7": "ADM3",
    "8": "PPL",
    "9": "PPLX",
    "10": "PPLX"
}

feature_code_map = {
    ("aeroway", "aerodrome"): "AIRP",
    ("aeroway", "helipad"): "AIRH",
    ("amenity", "bus_station"): "BUSTN",
    ("amenity", "clinic"): "HSP",
    ("amenity", "college"): "SCHC",
    ("amenity", "community_centre"): "BLDG",
    ("amenity", "courthouse"): "CTHSE",
    ("amenity", "embassy"): "DIP",
    ("amenity", "ferry_terminal"): "FY",
    ("amenity", "fire_station"): "BLDG",
    ("amenity", "grave_yard"): "CMTY",
    ("amenity", "hospital"): "HSP",
    ("amenity", "kindergarten"): "SCH",
    ("amenity", "library"): "LIBR",
    ("amenity", "place_of_worship"): "CH",
    ("amenity", "police"): "BLDG",
    ("amenity", "post_office"): "PO",
    ("amenity", "prison"): "PRN",
    ("amenity", "public_building"): "BLDG",
    ("amenity", "school"): "SCH",
    ("amenity", "theatre"): "BLDG",
    ("amenity", "townhall"): "BLDG",
    ("amenity", "university"): "SCHC",
    ("boundary", "administrative"): "PPL",
    ("boundary", "national_park"): "PRK",
    ("boundary", "protected_area"): "RESN",
    ("historic", "archaeological_site"): "HSTS",
    ("historic", "fort"): "FT",
    ("historic", "memorial"): "PRK",
    ("historic", "monument"): "MNMT",
    ("historic", "ruins"): "RUIN",
    ("historic", "tombstone"): "TMB",
    ("historic", "wreck"): "WRCK",
    ("historic", "yes"): "HSTS",
    ("landuse", "cemetery"): "CMTY",
    ("landuse", "commercial"): "MALL",
    ("landuse", "conservation"): "RESN",
    ("landuse", "forest"): "FRST",
    ("landuse", "industrial"): "BLDG",
    ("landuse", "meadow"): "PLN",
    ("landuse", "military"): "INSM",
    ("landuse", "mine"): "MN",
    ("landuse", "quarry"): "MN",
    ("landuse", "recreation_ground"): "PRK",
    ("landuse", "reservoir"): "RSV",
    ("landuse", "residential"): "PPL",
    ("landuse", "retail"): "MALL",
    ("landuse", "wood"): "FRST",
    ("leisure", "common"): "PRK",
    ("leisure", "garden"): "PRK",
    ("leisure", "golf_course"): "RECG",
    ("leisure", "golf_pin"): "RECG",
    ("leisure", "marina"): "MAR",
    ("leisure", "nature_reserve"): "PRK",
    ("leisure", "park"): "PRK",
    ("leisure", "pitch"): "PRK",
    ("leisure", "playground"): "PRK",
    ("leisure", "sports_centre"): "BLDG",
    ("leisure", "stadium"): "BLDG",
    ("leisure", "water_park"): "AMUS",
    ("man_made", "communications_tower"): "TOWR",
    ("man_made", "lighthouse"): "LTHSE",
    ("man_made", "pier"): "PIER",
    ("man_made", "telescope"): "ASTR",
    ("man_made", "tower"): "TOWR",
    ("man_made", "wastewater_plant"): "SWT",
    ("man_made", "water_tower"): "TOWR",
    ("man_made", "water_works"): "BLDG",
    ("man_made", "works"): "SWT",
    ("military", "airfield"): "AIRP",
    ("military", "nuclear_explosion_site"): "HSTS",
    ("natural", "bay"): "BAY",
    ("natural", "beach"): "BCH",
    ("natural", "cave_entrance"): "CAVE",
    ("natural", "cliff"): "CLF",
    ("natural", "crater"): "CRTR",
    ("natural", "geyser"): "GYSR",
    ("natural", "glacier"): "GLCR",
    ("natural", "heath"): "PLN",
    ("natural", "peak"): "MT",
    ("natural", "spring"): "SPNG",
    ("natural", "volcano"): "VLC",
    ("natural", "water"): "LK",
    ("natural", "waterfall"): "OVF",
    ("natural", "wetland"): "SWMP",
    ("natural", "wood"): "FRST",
    ("place", "city"): "PPL",
    ("place", "county"): "ADM2",
    ("place", "hamlet"): "PPL",
    ("place", "island"): "ISL",
    ("place", "islet"): "ISL",
    ("place", "locality"): "PPL",
    ("place", "neighborhood"): "PPL",
    ("place", "neighbourhood"): "PPL",
    ("place", "subdivision"): "PPL",
    ("place", "suburb"): "PPL",
    ("place", "town"): "PPL",
    ("place", "village"): "PPL",
    ("railway", "abandoned_station"): "RSTN",
    ("railway", "halt"): "RSTN",
    ("railway", "station"): "RSTN",
    ("railway", "subway_entrance"): "RSTN",
    ("railway", "tram_stop"): "RSTN",
    ("tourism", "artwork"): "PRK",
    ("tourism", "attraction"): "BLDG",
    ("tourism", "camp_site"): "CMP",
    ("tourism", "caravan_site"): "CMP",
    ("tourism", "hostel"): "HTL",
    ("tourism", "hotel"): "HTL",
    ("tourism", "motel"): "HTL",
    ("tourism", "museum"): "MUS",
    ("tourism", "picnic_site"): "PRK",
    ("tourism", "theme_park"): "AMUS",
    ("tourism", "zoo"): "ZOO",
    ("building", "yes"): "BLDG"
}
