default_types = {
    "default" : "BLDG"
}
use_types_map = {
    "Residential" : "HSE",
    "Worship" : "CTTR",
    "Educational" : "SCH",
    "Commercial": "BLDO",
    "Industrial" : "MFG",
    "Health": "HSP",
    "Transport":"BLDG",
    "Military":"INSM",
    "unknown": "BLDG"
}

use_sub_types_map = {
    "Apartments": "HSE",
    "Houses": "HSE",
    "Church" : "CH",
    "Synagogue" : "CTRR",
    "School": "SCH",
    "Railroad System" : "RSTN",
    "Bank" : "BANK",
    "Hotel":"HTL",
    "Library": "LIBR",
    "Freight House":"RSTN",
    "Hospital" : "HSP",
    "Lumber Yard":"MLSW",
    "Shop" : "RET",
    "Gallery": "MUS",
    "Pharmacy": "RET",
    "Cobbler" : "RET",
    "Office" : "BLDO",
    "Saw Mill" : "MLSW",
    "Distillery": "MFGB",
    "Warehouse" : "SHSE",
    "Storehouse": "SHSE",
    "Gas Works": "OILT",
    "Foundary": "FNDY",
    "Paper Mill": "ML",
    "Textile Mill": "ML",
    "Locomotive Works": "RYD",
    "Brewery" : "MFGB",
    "Factory" : "MFG",
    "Manufactory": "MFG",
    "Paint Shop": "MFG",
    "Rope Walk": "BLDG",
    "Slaughter House": "BLDG",
    "Asylum Insane" : "ASYL",
    "Asylum Inebriate": "ASYL",
    "Asylum Oprhan" : "BLDG",
    "Almshouse" : "BLDG",
    "Quarantine" : "BLDG",
    "Sanatorium" : "SNTR",
    "Toll House" : "BLDG",
    "Toll Gate" : "BLDG",
    "Railroad System" : "RSTN",
    "Railroad Depot" : "RSTN",
    "Subway Platform" :"MTRO",
    "Docks" : "DCKY",
    "Armory": "INSM",
    "Battery": "INSM",
    "Fortification": "FT"
}

 
